openapi: 3.0.0
info:
  title: Ecoomerce API
  description: Fully fledged node backend.
  version: 0.1.9
  contact: 
    email: vikas16898@gmail.com
    url: "https://abcd.com"
servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
 
 components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /:
    get:
      tags:
        - Home
      summary: Returns a greetings.
      responses:
        '200':    # status code
          description: A good success
          content:
            application/json:
              schema: 
                type: string
        '400':
          description: Bad Request.
        '500':
          description: Access Denied.